//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abacus.Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales_detail
    {
        public Sales_detail()
        {
            this.Products = new HashSet<Product>();
        }
    
        public int Id { get; set; }
    
        public virtual ICollection<Product> Products { get; set; }
        public virtual Sales_invoice Sales_invoice { get; set; }
    }
}
